name = "photographs"
main = "src/index.js"
compatibility_date = "2026-04-20"

[[r2_buckets]]
binding = "MEMORIES_BUCKET"
bucket_name = "photographs"

[vars]
ALLOWED_ORIGIN = "https://plumzy.github.io"
PUBLIC_READ = "true"
